brand: "Anypoint"
identifier: "e1c515f9-102d-4830-b353-18fe48065732"
categoryId:
- "49ed1d7f-9583-40aa-8e80-bfea709b16a4"
model: "Uniforms Modern Fit Short Sleeve Polo Shirt"
rating: 5
description: "Machine Wash, Tumble Dry. True to Size. Stretchable, waterproof and washable"
pictures:
- "https://images-na.ssl-images-amazon.com/images/I/41p0XBBb6vL.jpg"
price:
  amount:
    currency: "USD"
    currencyValue: 12.95
    name: "Amount"
  salesUnit:
    code: "EA"
    name: "EACH"
