#%RAML 1.0
title: Retail Product System API
version: v2.0
baseUri: http://localhost:8081/api

uses:
  product: /exchange_modules/org.mule.templates/retail-product/1.0.1/retail_product.raml
  taxonomy: /exchange_modules/org.mule.templates/retail-taxonomy/1.0.0/retail_taxonomy.raml

types:
  ProductResponse:
    type: product.Product
    description: |
      Product response

  ProductCollectionResponse:
    properties:
      products: product.Product[]
    description: |
      Product response collection

  ProductVariantCollectionResponse:
    properties:
      variants: product.ProductVariant[]
    description: |
      Product variant response collection

  ProductVariantResponse:
    type: product.ProductVariant
    description: |
      Product variant response

  CategoryCollectionResponse:
    properties:
      categories: taxonomy.Category[]
    description: |
      Category response collection

  CategoryResponse:
    type: taxonomy.Category
    description: |
      Category response    

/categories:
  description: |
    Working with categories
  get:
    displayName: Get categories
    description: Retrieve list of categories
    queryParameters:
      name?: string
      nocache?: boolean
    responses:
      200:
        description: Successful list of categories return
        body:
          application/json:
            type: CategoryCollectionResponse
            example: !include examples/category-collection-response.yaml
              
  /{categoryId}:
    uriParameters: 
      categoryId: string
    get:
      displayName: Get category
      description: Retrieve category specified by category Id
      queryParameters:
        nocache?: boolean
      responses: 
        200:
          description: Successful category return
          body:
            application/json:
              type: CategoryResponse
              example: !include examples/category-response.yaml

    /products:
      get:
        displayName: Get products for category
        description: Retrieve list of products for category
        queryParameters:
          nocache?: boolean
        responses:
          200:
            description: Successful list of products for category return
            body:
              application/json:
                type: ProductCollectionResponse
                example: !include examples/product-collection-response.yaml

/products:  
  description: | 
    Working with products
  get:
    displayName: Get products
    description: Retrieve list of products
    queryParameters:
      name?: string
      minPrice?: integer
      maxPrice?: integer
      nocache?: boolean
    responses:
      200:
        description: Successful list of products return
        body:
          application/json:
            type: ProductCollectionResponse
            example: !include examples/product-collection-response.yaml

  /{productId}:
    uriParameters:
      productId: string
    get:
      displayName: Get product  
      description: Retrieve product specified by product Id  
      responses: 
        200:
          description: Successful product return
          body:
            application/json:
              type: ProductResponse
              example: !include examples/product-response.yaml

    /variants:
      description: | 
        Working with variants
      get:
        displayName: Get variants 
        description: Retrieve list of variants 
        responses:
          200:
            description: Successful list of variants return
            body:
              application/json:
                type: ProductVariantCollectionResponse
                example: !include examples/variant-collection-response.yaml
                  
      /{variantId}:
        uriParameters:
          variantId: string
        get:
          displayName: Get variant  
          description: Retrieve variant specified by variant Id
          responses:
            200:
              description: Successful variant return
              body:
                application/json:
                  type: ProductVariantResponse
                  example: !include examples/variant-response.yaml
